# Generated by Django 3.2.6 on 2022-02-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
